/*
 * The one prop shape every icon in this directory uses.
 *
 * It lives here, beside the drawings, rather than in src/: src/ is generated by
 * scripts/sync.mjs and gitignored, so importing it from 2,142 checked-in
 * components would make them fail to typecheck on a fresh clone until a build
 * had run. sync.mjs re-exports this file instead, which keeps one definition.
 *
 * Declaring it per-file, which is what this replaced, cost 260 KB in the
 * published .d.ts: the declaration emitter cannot tell 2,142 structurally
 * identical interfaces apart, so it kept every one of them under a generated
 * name.
 *
 * This is a .ts, not a .tsx: sync.mjs treats every .tsx in here as an icon.
 */
import type { SVGProps } from "react";

/** Which of the four drawings the component renders. */
export type IconVariant = "Outline" | "TwoTone" | "Bold" | "Bulk";

/*
 * Nothing is omitted from SVGProps any more. `fill` and `width` used to be
 * taken over for "which drawing" and "stroke width", which cost the caller the
 * two real SVG attributes of those names; `variant` and `strokeWidth` say what
 * they mean and leave the element's own props alone.
 */
export interface IconProps extends SVGProps<SVGSVGElement> {
  /** Sizes and colours the glyph. Strokes are currentColor. */
  className?: string;
  /** Which drawing to render. */
  variant?: IconVariant;
  /** Stroke width, in the 24px drawing's own units. */
  strokeWidth?: string | number;
}
