/*
 * Writes the Vue package: one module per icon, a barrel, and the types.
 *
 * The drawings come from ../../icons/scripts/emit-svg.mjs, which renders the
 * built React components. Nothing here knows what an icon looks like, which is
 * the point: the artwork has one source, and it is not this file.
 *
 * Plain ESM, no compiler: the runtime builds its element with `h()`, so there
 * is no SFC to compile and no build step for a consumer to configure. dist is
 * what ships and what `exports` points at.
 *
 *   node scripts/build.mjs
 */
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { allSvgs, splitSvg, STYLES } from "../../icons/scripts/emit-svg.mjs";

const ROOT = fileURLToPath(new URL("../", import.meta.url));
const DIST = path.join(ROOT, "dist");

const icons = await allSvgs();

rmSync(DIST, { recursive: true, force: true });
mkdirSync(path.join(DIST, "icons"), { recursive: true });

/* The runtime is hand-written and copied rather than generated: it is the one
   file here a person is meant to read and change. */
writeFileSync(
  path.join(DIST, "runtime.js"),
  await import("node:fs").then((fs) =>
    fs.readFileSync(path.join(ROOT, "src", "runtime.js"), "utf8"),
  ),
);

const names = [];

for (const [name, drawings] of icons) {
  const split = Object.fromEntries(
    STYLES.map((style) => [style, splitSvg(drawings[style])]),
  );

  writeFileSync(
    path.join(DIST, "icons", `${name}.js`),
    `// AUTO-GENERATED - DO NOT EDIT\n` +
      `// Generated by scripts/build.mjs from @devigner-ui/icons\n` +
      `import { icon } from "../runtime.js";\n\n` +
      `export default /* #__PURE__ */ icon(${JSON.stringify(split)});\n`,
  );
  names.push(name);
}

writeFileSync(
  path.join(DIST, "index.js"),
  `// AUTO-GENERATED - DO NOT EDIT\n` +
    `// Generated by scripts/build.mjs\n\n` +
    names
      .map((n) => `export { default as Icon${n} } from "./icons/${n}.js";`)
      .join("\n") +
    "\n",
);

/*
 * One declaration file rather than 2,142: every icon is the same component
 * type, and the only thing a per-icon .d.ts would add is a second place for the
 * name list to go stale.
 */
writeFileSync(
  path.join(DIST, "index.d.ts"),
  `// AUTO-GENERATED - DO NOT EDIT\n` +
    `// Generated by scripts/build.mjs\n\n` +
    `import type { DefineComponent, SVGAttributes } from "vue";\n\n` +
    `export type IconStyle = ${STYLES.map((s) => `"${s}"`).join(" | ")};\n\n` +
    `export type IconName = ${names.map((n) => `"${n}"`).join(" | ")};\n\n` +
    `export interface IconProps extends SVGAttributes {\n` +
    `  /** Which of the four drawings to render. Defaults to "outline". */\n` +
    `  variant?: IconStyle;\n` +
    `  /** Stroke width, in the drawing's own units. Outline and twotone only. */\n` +
    `  strokeWidth?: string | number;\n` +
    `}\n\n` +
    `export type IconComponent = DefineComponent<IconProps>;\n\n` +
    names.map((n) => `export declare const Icon${n}: IconComponent;`).join("\n") +
    "\n",
);

console.log(`ok  ${names.length} Vue components, a barrel and types`);
