import fs from 'fs';
import path from 'path';

const ICONS_DIR = path.resolve('icons');
const SRC_DIR = path.resolve('src');

async function sync() {
  const watch = process.argv.includes('--watch');

  async function generate() {
    const files = fs.readdirSync(ICONS_DIR)
      .filter(f => f.endsWith('.tsx') && f !== 'index.tsx')
      .sort();

    console.log(`Syncing ${files.length} icons...`);

    // Generate barrel export (src/index.ts)
    const exports = files.map(file => {
      const name = file.replace('.tsx', '');
      const componentName = `Icon${name}`;
      return `export { default as ${componentName} } from '../icons/${name}';`;
    }).join('\n');

    /* The types have to leave through the entry point or they do not exist:
       the union below was generated for a year into a file nothing re-exported,
       while the README promised it. `export type` erases, so this costs the
       bundle nothing. */
    const indexContent = `// AUTO-GENERATED - DO NOT EDIT
// Generated by scripts/sync.mjs

export type { IconName, IconStyle, IconVariant, IconProps, IconComponentType } from './types';

${exports}
`;

    if (!fs.existsSync(SRC_DIR)) {
      fs.mkdirSync(SRC_DIR, { recursive: true });
    }

    fs.writeFileSync(path.join(SRC_DIR, 'index.ts'), indexContent);

    /*
     * types.ts, not types.d.ts: a declaration file is not part of the build
     * graph, so tsup never saw the old one and none of this reached anybody.
     *
     * IconProps is transcribed from what the generated components in icons/
     * actually accept. It used to be re-declared from a hand-written shell
     * component with a different prop model (`variant`, `size`, `strokeWidth`),
     * which is the API the docs described and no icon in the set implements.
     */
    const iconNames = files.map(f => f.replace('.tsx', ''));
    const typeContent = `// AUTO-GENERATED - DO NOT EDIT
// Generated by scripts/sync.mjs

import type { ForwardRefExoticComponent, RefAttributes } from 'react';
import type { IconProps, IconVariant } from '../icons/types';

export type IconName = ${iconNames.map(n => `'${n}'`).join(' | ')};

export type IconStyle = 'outline' | 'twotone' | 'bold' | 'bulk';

/* The same four drawings the \`variant\` prop names. IconStyle is the lowercase
   spelling the data files and URLs use; IconVariant is what the prop takes. */
export type { IconVariant };

/*
 * Re-exported, not redeclared. The definition lives in icons/types.ts, which
 * is what all 2,142 components import; two copies of this interface is how a
 * public type and the thing it describes drift apart.
 *
 * It extends the real <svg> props, so onClick, style, id, data-* and the aria
 * attributes reach the element instead of being dropped, \`width\` and \`fill\`
 * included, now that the drawing is picked by \`variant\` and the linework
 * weighed by \`strokeWidth\`.
 */
export type { IconProps };

/*
 * Not FC any more: every icon forwards its ref to the <svg>, which is what
 * Radix, Headless UI and every tooltip or popover trigger needs in order to
 * measure and position against it.
 */
export type IconComponentType = ForwardRefExoticComponent<
  IconProps & RefAttributes<SVGSVGElement>
>;

/* IconComponentType, not IconComponent: one of the icons is called Component,
   so IconComponent is the drawing. Same reason there is no IconMap alias, an
   icon is called Map. Write Record<IconName, IconComponentType>. */
`;

    fs.writeFileSync(path.join(SRC_DIR, 'types.ts'), typeContent);

    /*
     * One entry per icon, so `@devigner-ui/icons/Accessibility` resolves to a
     * module of its own. The drawings in icons/ export a default and nothing
     * else; these stubs are what put the named export on the subpath as well,
     * and they are generated into src/ so all 2,142 checked-in components stay
     * untouched. tsup.config.ts reads this directory for its entry list.
     */
    const entriesDir = path.join(SRC_DIR, 'entries');
    fs.rmSync(entriesDir, { recursive: true, force: true });
    fs.mkdirSync(entriesDir, { recursive: true });
    for (const name of iconNames) {
      fs.writeFileSync(
        path.join(entriesDir, `${name}.ts`),
        `export { default, default as Icon${name} } from '../../icons/${name}';\n`,
      );
    }

    // Generate styles.css
    const cssContent = `/* AUTO-GENERATED - DO NOT EDIT */
/* Generated by scripts/sync.mjs */

:root {
  --icon-size: 24px;
  --icon-stroke-width: 2;
  --icon-color: currentColor;
}

.icon {
  width: var(--icon-size);
  height: var(--icon-size);
  stroke-width: var(--icon-stroke-width);
  color: var(--icon-color);
  flex-shrink: 0;
}

`;

    fs.writeFileSync(path.join(SRC_DIR, 'styles.css'), cssContent);

    console.log(`Generated: src/index.ts, src/types.ts, src/styles.css`);
  }

  await generate();

  if (watch) {
    console.log('Watching for changes...');
    const chokidar = await import('chokidar');
    const watcher = chokidar.default.watch(ICONS_DIR, {
      ignored: /(^|[/\\])\../,
      persistent: true,
    });

    watcher.on('add', path => {
      console.log(`Added: ${path}`);
      generate();
    }).on('unlink', path => {
      console.log(`Removed: ${path}`);
      generate();
    }).on('change', path => {
      console.log(`Changed: ${path}`);
      generate();
    });
  }
}

sync().catch(console.error);