/*
 * Writes the Svelte package: one component per icon, the shared one they wrap,
 * and a barrel.
 *
 * The drawings come from ../../icons/scripts/emit-svg.mjs, which renders the
 * built React components. Nothing here knows what an icon looks like, which is
 * the point: the artwork has one source, and it is not this file.
 *
 * Source ships, not a bundle: a Svelte package is compiled by the consumer's
 * own toolchain, so `.svelte` files are the artefact and there is no build for
 * anyone to configure.
 *
 *   node scripts/build.mjs
 */
import { copyFileSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { allSvgs, splitSvg, STYLES } from "../../icons/scripts/emit-svg.mjs";

const ROOT = fileURLToPath(new URL("../", import.meta.url));
const DIST = path.join(ROOT, "dist");

const icons = await allSvgs();

rmSync(DIST, { recursive: true, force: true });
mkdirSync(path.join(DIST, "icons"), { recursive: true });

/* Hand-written and copied rather than generated: it is the one file here a
   person is meant to read and change. */
copyFileSync(
  path.join(ROOT, "src", "Icon.svelte"),
  path.join(DIST, "Icon.svelte"),
);

const names = [];

for (const [name, drawings] of icons) {
  const split = Object.fromEntries(
    STYLES.map((style) => [style, splitSvg(drawings[style])]),
  );

  writeFileSync(
    path.join(DIST, "icons", `${name}.svelte`),
    `<!-- AUTO-GENERATED - DO NOT EDIT -->\n` +
      `<!-- Generated by scripts/build.mjs from @devigner-ui/icons -->\n` +
      `<script>\n` +
      `  import Icon from "../Icon.svelte";\n\n` +
      `  const drawings = ${JSON.stringify(split)};\n\n` +
      `  export let variant = "outline";\n` +
      `  export let strokeWidth = null;\n` +
      `</script>\n\n` +
      `<Icon {drawings} {variant} {strokeWidth} {...$$restProps} />\n`,
  );
  names.push(name);
}

/*
 * A barrel of components, which is what `import { IconAdd } from "..."` needs.
 * Svelte files are not ESM until the consumer's compiler has been at them, so
 * this re-exports rather than defines.
 */
writeFileSync(
  path.join(DIST, "index.js"),
  `// AUTO-GENERATED - DO NOT EDIT\n` +
    `// Generated by scripts/build.mjs\n\n` +
    names
      .map((n) => `export { default as Icon${n} } from "./icons/${n}.svelte";`)
      .join("\n") +
    "\n",
);

writeFileSync(
  path.join(DIST, "index.d.ts"),
  `// AUTO-GENERATED - DO NOT EDIT\n` +
    `// Generated by scripts/build.mjs\n\n` +
    `import type { SvelteComponent } from "svelte";\n` +
    `import type { SVGAttributes } from "svelte/elements";\n\n` +
    `export type IconStyle = ${STYLES.map((s) => `"${s}"`).join(" | ")};\n\n` +
    `export type IconName = ${names.map((n) => `"${n}"`).join(" | ")};\n\n` +
    `export interface IconProps extends SVGAttributes<SVGSVGElement> {\n` +
    `  /** Which of the four drawings to render. Defaults to "outline". */\n` +
    `  variant?: IconStyle;\n` +
    `  /** Stroke width, in the drawing's own units. Outline and twotone only. */\n` +
    `  strokeWidth?: string | number | null;\n` +
    `}\n\n` +
    `export declare class IconComponent extends SvelteComponent<IconProps> {}\n\n` +
    names.map((n) => `export declare const Icon${n}: typeof IconComponent;`).join("\n") +
    "\n",
);

console.log(`ok  ${names.length} Svelte components, a barrel and types`);
