/*
 * Writes the React Native package: one module per icon, a barrel, and types.
 *
 * The drawings come from ../../icons/scripts/emit-svg.mjs, which renders the
 * built React components; parse.mjs turns each one into a tree of shapes,
 * because react-native-svg takes components and props rather than markup.
 *
 * Plain ESM, no bundler: Metro transforms node_modules, and per-icon modules
 * matter more here than on the web: Metro does not tree-shake, so importing
 * the whole barrel is a choice an app makes, not one this package makes for it.
 *
 *   node scripts/build.mjs
 */
import assert from "node:assert/strict";
import { copyFileSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { allSvgs, splitSvg, STYLES } from "../../icons/scripts/emit-svg.mjs";
import { parseSvgChildren, roundTrips, toRnTree } from "./parse.mjs";

const ROOT = fileURLToPath(new URL("../", import.meta.url));
const DIST = path.join(ROOT, "dist");

/* Every shape has to have a component to become. A tag with no entry here
   would render nothing at all, which is the one failure that would look like
   working software right up until an icon came out blank. */
const SUPPORTED = new Set([
  "path",
  "g",
  "circle",
  "ellipse",
  "rect",
  "defs",
  "clipPath",
]);

function assertSupported(nodes, where) {
  for (const node of nodes) {
    assert.ok(
      SUPPORTED.has(node.tag),
      `${where}: <${node.tag}> has no react-native-svg component`,
    );
    assertSupported(node.children, where);
  }
}

const icons = await allSvgs();

rmSync(DIST, { recursive: true, force: true });
mkdirSync(path.join(DIST, "icons"), { recursive: true });

copyFileSync(
  path.join(ROOT, "src", "runtime.js"),
  path.join(DIST, "runtime.js"),
);

const names = [];

for (const [name, drawings] of icons) {
  const styles = {};

  for (const style of STYLES) {
    const { attrs, inner } = splitSvg(drawings[style]);

    /* The parse is only as good as its inverse says it is. */
    assert.ok(roundTrips(inner), `${name} ${style} did not round-trip`);

    const nodes = parseSvgChildren(inner);
    assertSupported(nodes, `${name} ${style}`);

    styles[style] = { viewBox: attrs.viewBox, tree: toRnTree(nodes) };
  }

  writeFileSync(
    path.join(DIST, "icons", `${name}.js`),
    `// AUTO-GENERATED - DO NOT EDIT\n` +
      `// Generated by scripts/build.mjs from @devigner-ui/icons\n` +
      `import { icon } from "../runtime.js";\n\n` +
      `export default /* #__PURE__ */ icon(${JSON.stringify(styles)});\n`,
  );
  names.push(name);
}

writeFileSync(
  path.join(DIST, "index.js"),
  `// AUTO-GENERATED - DO NOT EDIT\n` +
    `// Generated by scripts/build.mjs\n\n` +
    names
      .map((n) => `export { default as Icon${n} } from "./icons/${n}.js";`)
      .join("\n") +
    "\n",
);

writeFileSync(
  path.join(DIST, "index.d.ts"),
  `// AUTO-GENERATED - DO NOT EDIT\n` +
    `// Generated by scripts/build.mjs\n\n` +
    `import type { ComponentType } from "react";\n` +
    `import type { SvgProps } from "react-native-svg";\n\n` +
    `export type IconStyle = ${STYLES.map((s) => `"${s}"`).join(" | ")};\n\n` +
    `export type IconName = ${names.map((n) => `"${n}"`).join(" | ")};\n\n` +
    `export interface IconProps extends SvgProps {\n` +
    `  /** Which of the four drawings to render. Defaults to "outline". */\n` +
    `  variant?: IconStyle;\n` +
    `  /** Width and height, in points. Defaults to 24. */\n` +
    `  size?: number | string;\n` +
    `  /** What \`currentColor\` resolves to. React Native has no cascade. */\n` +
    `  color?: string;\n` +
    `  /** Stroke width, in the drawing's own units. Outline and twotone only. */\n` +
    `  strokeWidth?: number | string;\n` +
    `}\n\n` +
    `export type IconComponent = ComponentType<IconProps>;\n\n` +
    names.map((n) => `export declare const Icon${n}: IconComponent;`).join("\n") +
    "\n",
);

console.log(
  `ok  ${names.length} React Native components, a barrel and types`,
);
